version: '2'
services:
  web:
    container_name: trading_app
    build: ./
    links:
      - db
    ports:
      - 4005:4005
    depends_on:
      - db
  db:
    container_name: trading_db
    image: mongo
    expose:
      - "27017"
    volumes:
        - mongodata:/data/db

volumes:
  mongodata:
